blank_issues_enabled: false
contact_links:
  - name: Contributing Guidelines
    url: https://github.com/openBookmarkz/ideas#readme
    about: Our organization offers a platform for users to submit innovative startup concepts, which can be further developed through open-source collaboration.
 
